
upstream api_server {
    server localhost:8080;
}

server {
    server_name _;
    listen 81;
    listen [::]:81;

    location = / { 
        return 200 "Am I captured?\nNo.\n";
    }

    location = /generate_204 {
        return 204;
    }
}

limit_req_zone $binary_remote_addr zone=captiveportalautologin:10m rate=1r/m;

server {
    server_name _;
    listen 80;
    listen [::]:80;

    proxy_buffering off;
    proxy_request_buffering off;

    location / {
        proxy_pass http://api_server;

        location /api/har {
            proxy_pass http://api_server;
            limit_req zone=captiveportalautologin burst=5 nodelay;
            limit_req_status 429;
            client_max_body_size 100M;
        }
    }
}
